import * as Print from 'expo-print';
// expo-file-system imported dynamically only on native
import type { Document } from '../types';

const DEMO_DOC_ID = 'demo-lease-agreement';

const LEASE_HTML = `
<html>
<head><meta charset="utf-8"><style>
  body { font-family: -apple-system, Helvetica, sans-serif; padding: 40px; color: #1a1a2e; line-height: 1.6; }
  h1 { font-size: 22px; text-align: center; margin-bottom: 30px; }
  h2 { font-size: 16px; margin-top: 20px; color: #333; border-bottom: 1px solid #eee; padding-bottom: 6px; }
  p { font-size: 13px; margin-bottom: 8px; }
  .clause { margin-left: 16px; }
  .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #999; }
</style></head>
<body>
  <h1>RESIDENTIAL LEASE AGREEMENT</h1>
  <p><strong>Between:</strong> Property Management SAS ("Landlord")<br>
  <strong>And:</strong> _________________ ("Tenant")</p>

  <h2>Article 1 - Property</h2>
  <p class="clause">The Landlord rents to the Tenant a furnished apartment located at 15 Rue de la Paix, 75002 Paris, France. The property consists of 2 rooms, kitchen, and bathroom (45 m2).</p>

  <h2>Article 2 - Duration</h2>
  <p class="clause">This lease is for a period of 1 year, from January 1, 2026 to December 31, 2026, renewable tacitly.</p>

  <h2>Article 3 - Rent</h2>
  <p class="clause">Monthly rent: 1,200.00 EUR, payable on the 1st of each month. Late payment penalty: 3% per month of delay.</p>

  <h2>Article 4 - Security Deposit</h2>
  <p class="clause">Security deposit: 2,400.00 EUR (2 months rent), payable upon signing.</p>

  <h2>Article 5 - Charges</h2>
  <p class="clause">Monthly charges provision: 150.00 EUR (water, building maintenance, garbage). Electricity and internet are tenant's responsibility.</p>

  <h2>Article 6 - Termination</h2>
  <p class="clause">Either party may terminate with 3 months written notice. Early termination by tenant requires payment of remaining months or finding a replacement tenant.</p>

  <h2>Article 7 - Insurance</h2>
  <p class="clause">Tenant must maintain home insurance covering fire, water damage, and civil liability. Proof required within 30 days of signing.</p>

  <p class="footer">This is a demo document generated by DocLear for demonstration purposes.</p>
</body>
</html>`;

export async function generateDemoPdf(): Promise<string | null> {
  try {
    const { uri } = await Print.printToFileAsync({ html: LEASE_HTML });
    return uri;
  } catch {
    return null;
  }
}

export function getDemoAnalysis(): Document {
  return {
    id: DEMO_DOC_ID,
    createdAt: new Date().toISOString(),
    title: 'Residential Lease Agreement — Paris',
    category: 'housing',
    docType: 'lease',
    docTypeLabel: 'Lease Agreement',
    status: 'new',
    summary:
      'A 1-year furnished apartment lease in Paris for 1,200 EUR/month with a 2,400 EUR security deposit. Contains a 3% late payment penalty and requires home insurance within 30 days.',
    whatIsThis:
      'This is a residential lease agreement between a property management company and a tenant for a furnished apartment in central Paris.',
    whatItSays:
      'You would rent a 45m2 furnished apartment at 15 Rue de la Paix for 1,200 EUR/month plus 150 EUR charges. Security deposit is 2,400 EUR. The lease runs from Jan 1 to Dec 31, 2026.',
    whatToDo: [
      'Review the late payment penalty clause (3% is high)',
      'Get home insurance before moving in (30-day deadline)',
      'Budget for total monthly cost: 1,350 EUR (rent + charges)',
      'Note the 3-month notice period for termination',
    ],
    deadline: '2026-01-31',
    deadlineDescription: 'Insurance proof required within 30 days of signing',
    urgency: 'medium',
    amounts: ['1,200 EUR/month', '2,400 EUR deposit', '150 EUR/month charges'],
    healthScore: 72,
    healthScoreExplanation:
      'Good standard lease but late payment penalty (3%) is above market average (1-2%). Early termination clause could be costly.',
    riskFlags: [
      {
        title: 'High late payment penalty',
        description:
          'The 3% monthly penalty for late payment is above the typical 1-2% in French leases.',
        severity: 'medium',
        page: 1,
        recommendation: 'Negotiate down to 1% or request a grace period of 10 days.',
      },
      {
        title: 'Early termination cost',
        description:
          'If you leave early, you must pay remaining months or find a replacement tenant yourself.',
        severity: 'high',
        page: 2,
        recommendation:
          'Ask for a clause allowing termination with 1 month penalty instead of all remaining months.',
      },
    ],
    positivePoints: [
      {
        title: 'Standard security deposit',
        description: '2 months deposit is the legal maximum for furnished rentals in France.',
      },
      {
        title: 'Charges included',
        description:
          'Water and building maintenance included in 150 EUR provision is reasonable for Paris.',
      },
    ],
    keyFacts: [
      'Monthly rent: 1,200 EUR + 150 EUR charges = 1,350 EUR total',
      'Security deposit: 2,400 EUR (2 months)',
      'Lease period: January 1 - December 31, 2026 (1 year, renewable)',
      'Late penalty: 3% per month — above market average',
      'Insurance required within 30 days of signing',
    ],
    suggestedQuestions: [
      'Is the late payment penalty legal in France?',
      'Can I negotiate the early termination clause?',
      'What insurance do I need exactly?',
    ],
    imageData: '',
    chatHistory: [],
    language: 'en',
    recommendations: [
      {
        type: 'website',
        title: 'ANIL — Housing Information',
        description: 'Free legal advice on French housing law',
        url: 'https://www.anil.org',
      },
    ],
  };
}

export { DEMO_DOC_ID };
